Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -11,23 +11,32 @@ jobs:
         runs-on: ubuntu-latest
         steps:
             - uses: actions/checkout@v4
+            
             - name: Configure Git Credentials
               run: |
-                  git fetch origin gh-pages --depth=1 
+                  git fetch origin gh-pages --depth=1 || echo "Failed to fetch gh-pages, continuing..."
                   git config user.name github-actions[bot]
                   git config user.email 41898282+github-actions[bot]@users.noreply.github.com
+              continue-on-error: true
+
             - uses: actions/setup-python@v5
               with:
                   python-version: 3.12.1
+
             - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
+
             - uses: actions/cache@v4
               with:
                   key: mkdocs-material-${{ env.cache_id }}
                   path: .cache
                   restore-keys: |
                       mkdocs-material-
-            - run: pip install -r requirements.txt
-            - run: mike deploy 0.0a1 stable
+
+            - name: Install Dependencies
+              run: pip install -r requirements.txt
+
+            - name: Deploy Documentation
+              run: mike deploy --push --update-aliases 0.1 stable
 
             - name: Set default version
-              run: mike set-default 0.0a1 stable
+              run: mike set-default --push 0.0a1 stable
